# Generated by Django 3.1.7 on 2021-04-18 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthRecord', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='H_User',
        ),
    ]
