# Generated by Django 3.1.7 on 2021-04-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthRecord', '0002_auto_20210418_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_user',
            name='first_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='h_user',
            name='last_name',
            field=models.CharField(max_length=140),
        ),
    ]
