# Generated by Django 3.1.7 on 2021-04-18 06:44

from django.db import migrations, models

# To run migration if in case there is required field with no value provided while running the program
def HealthPortal(*args,**kwargs):
    print("Welcome to your Health Portal!!")

class Migration(migrations.Migration):

    dependencies = [
        ('HealthRecord', '0003_auto_20210418_0031'),
    ]

    operations = [
        migrations.RunPython(HealthPortal,migrations.RunPython.noop),
        migrations.AddField(
            model_name='h_user',
            name='email',
            field=models.EmailField(default='default@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h_user',
            name='username',
            field=models.CharField(default='jdoe', max_length=70),
            preserve_default=False,
        ),
    ]
