# Generated by Django 3.1.7 on 2021-04-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthRecord', '0005_auto_20210418_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='h_user',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
