# Generated by Django 3.1.7 on 2021-04-21 02:19

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthRecord', '0006_h_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='h_user',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthRecord.address'),
        ),
    ]
