# Generated by Django 3.1.7 on 2021-04-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthRecord', '0007_auto_20210420_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
