# Generated by Django 3.1.7 on 2021-04-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthRecord', '0008_auto_20210420_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='dob',
            new_name='dateOfBirth',
        ),
    ]
