# Generated by Django 3.1.7 on 2021-04-21 04:58

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthRecord', '0009_auto_20210420_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='fname',
            field=models.CharField(help_text='First Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lname',
            field=models.CharField(help_text='Last Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default='', help_text='Includes 8-12 chars, contains (0-9), (a-z), one capital letter', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Primary Phone Number', max_length=31),
        ),
    ]
