# Generated by Django 3.1.7 on 2021-04-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthRecord', '0010_auto_20210420_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.TextField(default='', max_length=120)),
                ('weight', models.TextField(default='', max_length=120)),
                ('bmi_index', models.TextField(default='', max_length=120)),
                ('blood_pressure', models.TextField(default='', max_length=120)),
                ('prescription', models.TextField(default='', max_length=120)),
                ('immunization', models.TextField(default='', max_length=120)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthRecord.userdetails')),
            ],
        ),
    ]
